export const Genero = ['Masculino', 'Femenino', 'Prefiero no decirlo']

export const DiasLaborales = ['Lunes a viernes', 'Lunes a sabado', 'Lunes a domingo', 'Solo fines de semana']

export const Idiomas = ['Español', 'Inglés', 'Francés', 'Alemán', 'Italiano', 'Portugués', 'Chino (Mandarín)']

export const NivelIdiomas = ['Nativo', 'Principiante', 'Básico', 'Pre-Intermedio', 'Intermedio', 'Intermedio-Alto', 'Avanzado']

export const HabilidadesBlandas = [
  'Comunicación efectiva',
  'Trabajo en equipo',
  'Resolución de problemas',
  'Toma de decisiones',
  'Adaptabilidad',
  'Gestión del tiempo',
  'Habilidad para trabajar bajo presión',
  'Pensamiento crítico',
  'Creatividad',
  'Habilidades interpersonales',
  'Ética de trabajo',
  'Autoaprendizaje',
  'Proactividad',
  'Empatía',
  'Autoconocimiento',
  'Autogestión emocional',
  'Habilidades de escucha activa',
  'Liderazgo',
  'Negociación',
  'Gestión de conflictos',
  'Motivación',
  'Atención al detalle',
  'Habilidad para recibir y dar retroalimentación',
  'Habilidad para motivar a otros',
  'Compromiso',
  'Ética profesional',
  'Networking (crear y mantener relaciones profesionales)',
  'Multitarea',
  'Orientación al cliente'
]

export const HabilidadesTecnicas = [
  'Programación',
  'Desarrollo web',
  'Manejo de bases de datos',
  'Diseño gráfico',
  'Análisis de datos',
  'Redacción técnica',
  'Ingeniería de software',
  'Administración de proyectos',
  'Manejo de software de diseño CAD',
  'Marketing digital (SEO, SEM)',
  'Redes y administración de sistemas',
  'Contabilidad',
  'Auditoría',
  'Diseño UX/UI',
  'Operación de maquinaria especializada',
  'Labores de soldadura',
  'Gestión logística',
  'Diseño y arquitectura de redes',
  'Operación de software ERP (SAP, Oracle)',
  'Gestión de recursos humanos',
  'Traducción y interpretación',
  'Mecánica automotriz',
  'Biotecnología',
  'Ciberseguridad',
  'E-commerce',
  'Desarrollo móvil (Android, iOS)',
  'Automatización industrial',
  'Diseño 3D y animación'
]

export const Discapacidades = [
  'Discapacidad auditiva',
  'Discapacidad del desarrollo',
  'Discapacidad del habla y el lenguaje',
  'Discapacidad física',
  'Discapacidad intelectual',
  'Discapacidad invisible',
  'Discapacidad neurológica',
  'Discapacidad psicosocial',
  'Discapacidad sensorial',
  'Discapacidad visual'
]

export const TipoContrato = ['Contrato por tiempo determinado', 'Contrato por tiempo indeterminado', 'Contrato para becario/practicante']

export const Escolaridad = ['Sin estudios', 'Sabe leer y escribir', 'Primaria', 'Secundaria', 'Bachillerato', 'Bachillerato Técnico', 'Técnico Superior Universitario', 'Licenciatura/Ingeniería', 'Posgrado', 'Maestría', 'Doctorado']

export const Prestaciones = [
  'Apoyo económico para transporte',
  'Apoyos por defunción',
  'Área antiestrés',
  'Asistencia nutricional y programas de salud',
  'Bono por productividad',
  'Bono por puntualidad',
  'Check-up médico',
  'Fondo de ahorro',
  'Gimnasio',
  'Guardería',
  'Planes de formación',
  'Prestaciones de Ley',
  'Seguro de gastos médicos',
  'Servicio de comedor',
  'Servicio de transporte de personal',
  'Servicios deportivos y culturales',
  'Vales de comida',
  'Vales de despensa',
  'Vales de gasolina',
  'Vehículo'
]

export const CausaVacante = ['Empresa nueva', 'Necesidades temporales de mano de obra', 'Puesto de nueva creación', 'Reposición del personal']

export const JORNADA_LABORAL = ['Por horas', 'Por tarea completada/destajo', 'Fines de semana', 'Turno nocturno', 'Medio tiempo (4 hrs)', 'Tiempo completo (8 hrs)', 'Turnos rotativos/Jornadas rotativas']

export const PERIODO_PAGO = ['Por tarea completada/destajo', 'Semanal', 'Decenal', 'Catorcenal', 'Quincenal', 'Mensual']

export const AreaEmpresa = [
  'Administración',
  'Asuntos jurídicos',
  'Calidad',
  'Comercialización',
  'Dirección general',
  'Finanzas y Contabilidad',
  'Informática',
  'Logística',
  'Mantenimiento industrial',
  'Operativo',
  'Producción',
  'Publicidad y Mercadotecnia',
  'Recursos humanos'
]

export const AREA_EMPRESA_FILTROS = [
  'Todas',
  'Administración',
  'Asuntos jurídicos',
  'Calidad',
  'Comercialización',
  'Dirección general',
  'Finanzas y Contabilidad',
  'Informática',
  'Logística',
  'Mantenimiento industrial',
  'Operativo',
  'Producción',
  'Publicidad y Mercadotecnia',
  'Recursos humanos'
]

export const MUNICIPIOS = [
  'Municipios',
  'Abasolo',
  'Acámbaro',
  'San Miguel de Allende',
  'Apaseo el Alto',
  'Apaseo el Grande',
  'Atarjea',
  'Celaya',
  'Manuel Doblado',
  'Comonfort',
  'Coroneo',
  'Cortazar',
  'Cuerámaro',
  'Doctor Mora',
  'Dolores Hidalgo Cuna de la Independencia Nacional',
  'Guanajuato',
  'Huanímaro',
  'Irapuato',
  'Jaral del Progreso',
  'Jerécuaro',
  'León',
  'Moroleón',
  'Ocampo',
  'Pénjamo',
  'Pueblo Nuevo',
  'Purísima del Rincón',
  'Romita',
  'Salamanca',
  'Salvatierra',
  'San Diego de la Unión',
  'San Felipe',
  'San Francisco del Rincón',
  'San José Iturbide',
  'San Luis de la Paz',
  'Santa Catarina',
  'Santa Cruz de Juventino Rosas',
  'Santiago Maravatío',
  'Silao de la Victoria',
  'Tarandacuao',
  'Tarimoro',
  'Tierra Blanca',
  'Uriangato',
  'Valle de Santiago',
  'Victoria',
  'Villagrán',
  'Xichú',
  'Yuriria'
]
export const MUNICIPIOSM = [
  'Abasolo',
  'Acámbaro',
  'San Miguel de Allende',
  'Apaseo el Alto',
  'Apaseo el Grande',
  'Atarjea',
  'Celaya',
  'Manuel Doblado',
  'Comonfort',
  'Coroneo',
  'Cortazar',
  'Cuerámaro',
  'Doctor Mora',
  'Dolores Hidalgo Cuna de la Independencia Nacional',
  'Guanajuato',
  'Huanímaro',
  'Irapuato',
  'Jaral del Progreso',
  'Jerécuaro',
  'León',
  'Moroleón',
  'Ocampo',
  'Pénjamo',
  'Pueblo Nuevo',
  'Purísima del Rincón',
  'Romita',
  'Salamanca',
  'Salvatierra',
  'San Diego de la Unión',
  'San Felipe',
  'San Francisco del Rincón',
  'San José Iturbide',
  'San Luis de la Paz',
  'Santa Catarina',
  'Santa Cruz de Juventino Rosas',
  'Santiago Maravatío',
  'Silao de la Victoria',
  'Tarandacuao',
  'Tarimoro',
  'Tierra Blanca',
  'Uriangato',
  'Valle de Santiago',
  'Victoria',
  'Villagrán',
  'Xichú',
  'Yuriria'
]

export const MUNICIPIOS_FILTROS = [
  'Todos',
  'Abasolo',
  'Acámbaro',
  'San Miguel de Allende',
  'Apaseo el Alto',
  'Apaseo el Grande',
  'Atarjea',
  'Celaya',
  'Manuel Doblado',
  'Comonfort',
  'Coroneo',
  'Cortazar',
  'Cuerámaro',
  'Doctor Mora',
  'Dolores Hidalgo Cuna de la Independencia Nacional',
  'Guanajuato',
  'Huanímaro',
  'Irapuato',
  'Jaral del Progreso',
  'Jerécuaro',
  'León',
  'Moroleón',
  'Ocampo',
  'Pénjamo',
  'Pueblo Nuevo',
  'Purísima del Rincón',
  'Romita',
  'Salamanca',
  'Salvatierra',
  'San Diego de la Unión',
  'San Felipe',
  'San Francisco del Rincón',
  'San José Iturbide',
  'San Luis de la Paz',
  'Santa Catarina',
  'Santa Cruz de Juventino Rosas',
  'Santiago Maravatío',
  'Silao de la Victoria',
  'Tarandacuao',
  'Tarimoro',
  'Tierra Blanca',
  'Uriangato',
  'Valle de Santiago',
  'Victoria',
  'Villagrán',
  'Xichú',
  'Yuriria'
]

export const EXPERIENCIA_LABORAL = ['Sin experiencia laboral', 'Menos de 6 meses', '6 meses - 1 año', '1 año - 2 años', '2 años - 3 años', '3 años - 5 años', '5 años - 7 años', '7 años - 10 años', 'Más de 10 años']

export const MODALIDAD = ['Híbrida', 'Presencial', 'Virtual']
