export const habilidadesBlandas = [
    "Adaptabilidad",
    "Adaptabilidad a entornos virtuales",
    "Adaptabilidad a los cambios",
    "Adaptabilidad al cambio tecnológico",
    "Adaptabilidad cultural",
    "Adaptabilidad tecnológica",
    "Agilidad mental",
    "Análisis de datos",
    "Análisis de mercado",
    "Análisis e interpretación de información",
    "Aprendizaje activo",
    "Aprendizaje continuo",
    "Atención a los detalles",
    "Autoconfianza",
    "Autocontrol",
    "Autogestión del aprendizaje",
    "Capacidad de aprendizaje",
    "Colaboración",
    "Compromiso",
    "Comunicación asertiva",
    "Comunicación efectiva",
    "Comunicación intercultural",
    "Comunicación persuasiva",
    "Conciliación",
    "Construcción de relaciones",
    "Cooperación",
    "Creatividad",
    "Delegación de tareas",
    "Desarrollo de estrategias de marketing",
    "Destreza manual",
    "Diseño de experiencia del cliente",
    "Empatía",
    "Empatía cultural",
    "Empatía laboral",
    "Escucha activa",
    "Espíritu emprendedor",
    "Ética profesional",
    "Facilidad de hablar en público",
    "Facilidad de palabra",
    "Facilidad para aprender idiomas",
    "Facilitación de grupos",
    "Facilitación de reuniones",
    "Flexibilidad",
    "Gestión de conflicto",
    "Gestión de conflictos interpersonales",
    "Gestión de equipos",
    "Gestión de la cadena de suministro",
    "Gestión de la calidad",
    "Gestión de la diversidad",
    "Gestión de la información",
    "Gestión de proveedores",
    "Gestión de proyectos",
    "Gestión de recursos",
    "Gestión de riesgos",
    "Gestión del cambio",
    "Gestión del conocimiento",
    "Gestión del rendimiento",
    "Gestión del talento",
    "Gestión del tiempo",
    "Habilidades de coaching",
    "Habilidades de negociación",
    "Habilidades de presentación",
    "Habilidades de servicio al cliente",
    "Habilidades financieras básicas",
    "Honestidad",
    "Iniciativa",
    "Innovación",
    "Innovación centrada en el cliente",
    "Integridad",
    "Inteligencia artificial y aprendizaje automático",
    "Inteligencia emocional",
    "Lectura y redacción",
    "Liderazgo",
    "Manejo de grupos de trabajo",
    "Manejo de información confidencial",
    "Mentalidad resolutiva",
    "Mentoría",
    "Motivación",
    "Multitareas",
    "Negociación",
    "Networking",
    "Organización",
    "Organización de eventos",
    "Orientación a resultado",
    "Orientación a resultados",
    "Orientación al cliente",
    "Orientación al cliente interno",
    "Orientación al detalle",
    "Orientación al logro",
    "Orientación al servicio",
    "Pensamiento analítico",
    "Pensamiento conceptual",
    "Pensamiento creativo",
    "Pensamiento crítico",
    "Pensamiento crítico en situaciones de crisis",
    "Pensamiento estratégico",
    "Pensamiento lateral",
    "Pensamiento reflexivo",
    "Pensamiento sistémico",
    "Persuasión",
    "Planeación estratégica",
    "Razonamiento deductivo e inductivo",
    "Razonamiento espacial",
    "Razonamiento lógico",
    "Razonamiento lógico - matemático",
    "Relaciones interpersonales",
    "Relaciones públicas",
    "Resiliencia",
    "Resolución de conflictos",
    "Resolución de problemas",
    "Resolución de problemas complejos",
    "Resolución de problemas de manera colaborativa",
    "Resolución de problemas de manera creativa",
    "Resolución de problemas éticos",
    "Resolución de problemas técnicos",
    "Respeto",
    "Responsabilidad social",
    "Responsable",
    "Socioemocionales",
    "Solución de problemas",
    "Supervisión y administración del personal",
    "Tolerancia a la diversidad",
    "Tolerancia a la frustración",
    "Tolerancia al estrés",
    "Toma de decisiones",
    "Trabajo bajo presión",
    "Trabajo en entornos multiculturales",
    "Trabajo en equipo",
    "Trabajo independiente",
];